name = input("Your name: ")
age = input("Your age: ")
dob = input("Date of birth (dd-mm-yyyy): ")
gender = input("Gender [M/F]: ")
mob = input("Mobile No.: ")
email = input("Email-id: ")

print("Name:".ljust(20), name)
print("Age:".ljust(20), age)
print("DOB:".ljust(20), dob)
print("Gender (M/F):".ljust(20), gender)
print("Mobile No.:".ljust(20), mob)
print("Email-id:".ljust(20), email)